config/routes.rb
# typed: strict
Rails.application.routes.draw do
  get 'welcome/index'

  resources :ramens

  root 'welcome#index'
end

app/models/application_record.rb
# typed: strong
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ramen.rb
# typed: strong
class Ramen < ApplicationRecord
end

app/controllers/application_controller.rb
# typed: strong
class ApplicationController < ActionController::Base
end

app/controllers/ramens_controller.rb
# typed: strict
class RamensController < ApplicationController
  extend T::Sig

  sig {void}
  def initialize()
    @ramen = T.let(nil, T.nilable(Ramen))
  end

  sig {returns(Ramen)}
  def show
    @ramen = Ramen.find(params[:id])
  end

  sig {returns(NilClass)}
  def new
  end

  sig {returns(String)}
  def create
    @ramen = Ramen.new(ramen_params)

    @ramen.save
    redirect_to @ramen
  end

  private

  sig {returns(ActionController::Parameters)}
  def ramen_params
    params.require_typed(:ramen, TA[ActionController::Parameters].new).permit(:brand, :review)
  end
end

app/controllers/welcome_controller.rb
# typed: strong
class WelcomeController < ApplicationController
  extend T::Sig
  sig {returns(NilClass)}
  def index
  end
end

app/helpers/application_helper.rb
# typed: strong
module ApplicationHelper
end

app/helpers/ramens_helper.rb
# typed: strong
module RamensHelper
end

app/helpers/welcome_helper.rb
# typed: strong
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RamenRailsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/ramens/new.html.erb
<h1>New Ramen</h1>

<%= form_with scope: :ramen, url: ramens_path, local: true do |form| %>
  <p>
    <%= form.label :brand %><br>
    <%= form.text_field :brand %>
  </p>
 
  <p>
    <%= form.label :review %><br>
    <%= form.text_area :review %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/ramens/show.html.erb
<p>
  <strong>Brand:</strong>
  <%= @ramen.brand %>
</p>
 
<p>
  <strong>Review:</strong>
  <%= @ramen.review %>
</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>